warthog_velocity_controller:
  linear:
    x:
      has_acceleration_limits: true
      max_acceleration       : 5.0   # m/s^2
  angular:
    z:
      has_acceleration_limits: true
      max_acceleration       : 4.0   # rad/s^2
